### ISSUE TITLE
Failing to connect to the API

### ISSUE THREAD

**Issue by gledim** [sipcapture/homer-view#10]
We are trying to deploy the latest version of the View, with the proxy residing in the same container where View is running, but we get a 404 for **/api/v3/auth**

The installation was done from source, based on the README guide, and the View is started with:
**ng serve --host=0.0.0.0 --disable-host-check**

**Comment by RFbkak37y3kIY** [comment]
fixed, on Eduard-dev branch, waiting merge to master

**Comment by adubovikov** [comment]
merged

**Comment by lmangani** [comment]
@gledim please retest and update the ticket whenever possible

**Comment by gledim** [comment]
Hi guys, after a bit of ironing, we were able to deploy the application in a kubernetes pod, where both proxy and the view application are running in the same container.

Now we are getting HTTP 400 errors for some components of the /api/v3/, with the reason "Missing or malformed JWT"

For example:

`core.js:6014 ERROR Error: Uncaught (in promise): HttpErrorResponse: {"headers":{"normalizedNames":{},"lazyUpdate":null},"status":400,"statusText":"Bad Request","url":"http://homer7-app.query.consul/api/v3/call/report/qos","ok":false,"name":"HttpErrorResponse","message":"Http failure response for http://homer7-app.query.consul/api/v3/call/report/qos: 400 Bad Request","error":{"message":"missing or malformed jwt"}}
    at resolvePromise (zone-evergreen.js:797)
    at resolvePromise (zone-evergreen.js:754)
    at zone-evergreen.js:858
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:39680)
    at ZoneDelegate.invokeTask (zone-evergreen.js:390)
    at Zone.runTask (zone-evergreen.js:168)
    at drainMicroTaskQueue (zone-evergreen.js:559)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:469)
    at invokeTask (zone-evergreen.js:1603)
`

We have constructed the request URL with an ID included, the message ID that we got from a search in Homer-app. 
Is this the correct ID?

**Comment by adubovikov** [comment]
are you forwarding the Authentication header ?

**Comment by gledim** [comment]
From inspecting the HTTP traffic that homer-app is receiving, we don't see the Authentication header included. 
Shouldn't the proxy include it?

These are the lines we have added to **app.components.ts** along with the rest of the steps in the README


> import { AuthenticationService, CallTransactionService, SearchCallService } from './services';
> ...
> import { first } from 'rxjs/operators';
> ...
> 	        this.authenticationService.currentUser.subscribe(async (user) => {
>             if (!user) {
>                 /* FOR TEST API  --> Here add your API user and password .logn('user', 'password') */
>                 await this.authenticationService.login('usnername', 'pass').pipe(first()).toPromise();
>                 return;
>             }});

**Comment by gledim** [comment]
Hi team,

We have upgraded our homer-app deployment to the latest version, but we are still seeing the same issue as above.

Anything we might have missed?

**Comment by jacovinus** [comment]
Hello @gledim  can you please recheck if in 

`./enviroment.ts `  in your `apiUrl` there is the Proxy address

and in `proxy.config.js`  is a path to your **Homer** backend?

**Comment by gledim** [comment]
Hi @jacovinus 

Yes,

this is the `environment.ts`:

import { VERSION } from '../VERSION';
export const environment = {
  production: false,
  environment: VERSION + '(dev)',
  apiUrl: 'http://localhost/api/v3'
}


and this is `proxy/config.js`:

var config = {
        debug: true,
        apiUrl: 'http:/*homer-app URL*/',
        apiSess: 'http://*homer-app URL*/api/v3/auth',
        apiAuthJWT: true,
        apiUser: '*username*',
        apiPass: '*password*',
        timeOut: 1800,
        proxyHost: 'http://localhost',
        proxyPort: 8765
};
module.exports = config;

We have used `localhost` for the proxy address, as it is running in the same container as `homer-view`.

**Comment by jacovinus** [comment]
Try setting `http://localhost:8765/api/v3`  as apiUrl on environment.ts (adding proxy port on address)

**Comment by gledim** [comment]
These are the latest console errors:

![image](https://user-images.githubusercontent.com/36967612/79490447-2ae0bd80-801d-11ea-97e1-52cb946c623d.png)

**Comment by jacovinus** [comment]
@gledim, thanks for your time.

We just fixed issue and updated documentation.

Have to update your Homer-view from this repo and follow steps.

On `environment.ts` will just have to set `http://localhost:8765` instead of ` http://localhost:8765/api/v3`

**Comment by gledim** [comment]
Thank you for all the help @jacovinus 
After pulling the most recent version and applying the necessary configs, we don't see any errors in the console, and the interface seems to load some other elements, but it's not displaying any relevant info.

![image](https://user-images.githubusercontent.com/36967612/79621163-ae300b00-8112-11ea-9b29-ac9308cfb57f.png)

We have structured the URL as required, about a call that we could find in the homer-app, but we are not completely sure about the ID. 
We tried using the Message ID and the Call ID(along with the same value in callid) but the results were the same.
We also tried to explicitly define the tabs, without success. 
Any idea what might be the issue?

**Comment by jacovinus** [comment]
Good morning @gledim , the Id needed is the id inside the data response. 

You can find it  **behind** the `from_user` data.

Or if have access to Homer-app or Homer-ui, inside the call details:

<img width="498" alt="Screenshot 2020-04-18 at 07 44 40" src="https://user-images.githubusercontent.com/30432825/79629424-fa4a7200-8149-11ea-97ab-79064ed9ac56.png">

**Comment by gledim** [comment]
Hi @jacovinus, that seems to correspond to the Message ID that we were trying earlier, without success.

We run a packet capture in the host, and we see that homer-app is responding with 201s, but the JSON that it returns is empty.

Basically, we are constructing the URL with the ID of a message, the callID for the dialog, along with from and to in GMT, converted to millisecond epoch.

**Comment by jacovinus** [comment]
Hi @gledim, are you using the timestamps of the request payload in the header network tab?
The Empty JSON object returns when the timestamps "from" and "to" does not match with the ones of the payload (means that the call were not made in that time range).
<img width="321" alt="Screenshot 2020-04-19 at 09 17 24" src="https://user-images.githubusercontent.com/30432825/79681964-c2612e80-821e-11ea-9f78-05ea3f9b35f7.png">
<img width="380" alt="Screenshot 2020-04-19 at 09 17 13" src="https://user-images.githubusercontent.com/30432825/79681968-c7be7900-821e-11ea-875f-3bda6fbe3c0a.png">

**Comment by gledim** [comment]
Hi @jacovinus thank you very much for you help.
That was the last remaining part for us to get results in the view
