### ISSUE TITLE
Split IP:port correctly for both IPv4 and IPv6 addresses

### ISSUE THREAD

**Issue by systemcrash** [sipcapture/homer-view#15]
https://github.com/sipcapture/homer-view/blob/9905979d612370790670e3864599944d4081bc64/src/app/components/detail-dialog/tab-flow/tab-flow.component.ts#L114

Recommend a new regex here. 

https://regexr.com/3hpvt

**Comment by lmangani** [comment]
@systemcrash spot on, this was also fixed in HOMER but i think it was not yet ported here. Feel free to submit a PR and get the credit! :)

**Comment by systemcrash** [comment]
(I run the 'latest' homer, and, if it is fixed there, it certainly doesn't seem like it)

I am trying out code to submit....

**Comment by systemcrash** [comment]
#17 addresses this
