### ISSUE TITLE
Flow tab: Address header row does not follow left-right scrolling on wide call graphs. 

### ISSUE THREAD

**Issue by systemcrash** [sipcapture/homer-view#16]
Scroll left or right, and the header row remains fixed while the vertical lines pointing to them scroll away to the left or right.....

**Comment by lmangani** [comment]
Thanks - Could you please attach a screenshot so our guys can patch this up?

**Comment by systemcrash** [comment]
Probably the same as

https://github.com/sipcapture/homer-ui/issues/223
