### ISSUE TITLE
The View doesn't load when run as Prod

### ISSUE THREAD

**Issue by gledim** [sipcapture/homer-view#30]
Hi guys,

We have noticed that the new version of Homer-View, the one using Angular 10, is not working properly when run as prod.

The same software, with only a change in host URLs runs fine when run as Dev, but when run with `--prod` switch, it fails to load the JS files:

![image](https://user-images.githubusercontent.com/36967612/109231740-66185500-77c7-11eb-8ecc-6f7e551395d3.png)

The JSON with data gets loaded correctly, as inspected through explorer, but the main issue seems to be with the above files.

We have tried tweaking this in a few ways, without success. Have you seen this before?

**Comment by adubovikov** [comment]
@jacovinus @AlexeyOplachko can you please check it ?

**Comment by jacovinus** [comment]
Hi @gledim , I just did a new git clone, installed npm packages for angular and for the proxy, did the configuration, served as regular configuration, served as production, ran build and served on an http server the /dist folder and I'm not having that issues. 
Maybe if we check step by step what has been done, can find the issue. 
The simplest thing can think is maybe that the local version of angular is different from the one of the project
 (check by running ``ng --version`` on root and comparing with original package.json). 
Also check the Proxy has been configured and installed (and runned).   
Other one could be the serving of production env its `` ng serve --configuration=production``, 
for building in this case is ``npm run build`` and then serving with an http server as ``dist/homer-view`` 
ex: `` npx http-server dist/homer-view`` . 
Maybe if we have some more detailed information about process, as said, can fix it better :)

**Comment by gledim** [comment]
Hi @jacovinus, thank you for checking on this. 
We actually don't build it, as we have encountered issues earlier, and the quickest solution was to just serve it, however, I'm open to explore this as well.
Based on your suggestions, I made sure that the global and local versions match completely. We had a small discrepancy in the CLI version, but it didn't seem to be the issue.
The proxy is up and running, and was actually the first thing that I checked, due to issues happening with it in the past.
I didn't try the third one, however, a difference that I noticed pre and post the update, was the builder used. 
In an earlier version, it's used `@angular-devkit/build-angular`, while now it is `ngx-build-plus`. I tried rolling this back, but it didn't work as well.

So, we are deploying this in a Kubernetes, for both dev and prod. The configurations are exactly the same, with the only differences being the packages installed from `packages.json` and `environments*.ts files`. 
We use a simple Docker file that builds upon `node:10-alpine` image, installs npm, and runs a shell script that starts the proxy and does a `ng --server` depending on the environment, for dev or prod.
I hope I was clear, but please let me know if I can provide more info on anything :)

**Comment by jacovinus** [comment]
Hi @gledim, can you provide us...
1- Actual discrepancy between global and local CLI versions
2- More details about the Docker config
3- More details about the script you used for starting proxy and angular application
... to reproduce your issue? 
Also, did you try yet using a build version with angular 10? (to check if you still having issues about that)
errors captured  messages on browser console or on terminal are very appreciated :)

**Comment by lmangani** [comment]
@gledim our versions are built with node 12.x alpine. I would suggest using that.

**Comment by gledim** [comment]
Thank you @jacovinus and @lmangani, we have been using node 12.x alpine image, but I downgraded to 10 just to test it out.
Now I'm back to the latest version, node:12.21.0-alpine

I have defined the global CLI version in the Docker file, so the alert no longer showed up, but also without success

Attached is the Dockerfile and the script, they are very basic.

Strangely, the CLI shows no errors at all. It stops pushing logs right after the compilation ends. The browser doesn't throw any errors as well, the only weird thing is the image in the initial post.

The only warnings that I see in logs are:

`WARNING in /usr/src/app/src/VERSION.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
WARNING in /usr/src/app/src/app/services/proxy.service.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
WARNING in /usr/src/app/src/app/services/statistic.service.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
WARNING in /usr/src/app/src/app/services/export/proto.service.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
WARNING in /usr/src/app/src/app/services/export/registration.service.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
WARNING in /usr/src/app/src/environments/environment.prod.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
WARNING in /usr/src/app/node_modules/ng2-charts/__ivy_ngcc__/fesm2015/ng2-charts.js depends on 'chart.js'. CommonJS or AMD dependencies can cause optimization bailouts.`

[files.zip](https://github.com/sipcapture/homer-view/files/6112037/files.zip)


Yes, I have pulled the update from Sep 2020, that I think makes the switch to Angular 10, that's when the issues begun.

Please let me know if there is something else that I can test or provide more info :)

**Comment by jacovinus** [comment]
thank you very much @gledim we will be taking a look at your files and solving the issues :)

**Comment by gledim** [comment]
Thank you @jacovinus, please let me know whenever I can help with something :)

I just wanted to add a detail, that I think I haven't mentioned earlier:
From console log, from the request sent to `/call/transaction` the correct JSON is received, but it fails to get processed.

**Comment by jacovinus** [comment]
@gledim, fixed Angular 10 issues on build with https://github.com/sipcapture/homer-view/commit/9e1d77792b781696a5fba7d61fb348061917880e, please pull changes, remove ``node_modules`` folder, ``dist`` folder,  run ``npm install`` for the main Angular project. ``npm run build``, and try your setup with the built version  on /dist folder together with the proxy  :)

**Comment by gledim** [comment]
Hi @jacovinus, thank you for the updates. I pulled and built locally, which managed me to have better visibility.

The issue still happens, but I think it might not be due to the configuration of homer-view. In my local setup, I noticed that when I pointed the Proxy to the dev homera-app, it worked perfectly, but when I pointed to the prod one, the issue happens. 
Previously I was using an auto-discovery FQDN, that has caused the initial confusion.

By analyzing the traffic that the Proxy, View and API exchange between each other, I noticed an anomaly in the response for QoS.

When the Dev instance of API is queried, it returns an empty JSON when there is no QoS information, such as below:

```{"rtcp":{"data":[],"total":0},"rtp":{"data":[],"total":0}}```

but when the Prod instance is queried, nothing is returned. 

And this sends us back at something that I was going to check in homer-app, because it was not showing the QoS information when opened in Prod.
I did a quick verification, and it's the same situation happening with the QoS tab in homer-app in Prod, so no JSON, while in DEV there is a JSON, even when it has no data.

Do you have any idea why this is happening, and how can we fix it? 

The post is a bit long, but I hope I was clear enough :)

**Comment by gledim** [comment]
Hey @jacovinus 
I just wanted to let you know, that since I think the issue is coming from homer-app, I managed to make a fork of homer-ui, and modify it's Angular 10 setup as in https://github.com/sipcapture/homer-view/commit/9e1d77792b781696a5fba7d61fb348061917880e
but it didn't work

**Comment by gledim** [comment]
We haven't been able to replicate this with the latest updates
